implement almost functions with out logging
piedra-de-flor/shortURL pull request #1
Opened 2023-08-12 17:44 UTC by piedra-de-flor

2023-09-27 06:36 UTC, kakao-gray-great requested changes
안녕하세요 영우님 ~~
미션 하시느라 고생하셨습니다!

몇 가지 리뷰 남겼으니 확인 부탁드립니다!

추가로 예외에 대한 테스트가 많이 부족한 것 같은데 챙겨주시면 좋을 것 같아요.

2023-09-27 06:36 UTC, kakao-gray-great commented on src/main/java/com/example/shortURL/configuration/RepositoryConfig.java
> +*/
사용 안하는건 지워주시죠ㅎ

2023-09-27 06:36 UTC, kakao-gray-great commented on src/main/java/com/example/shortURL/controller/UrlController.java
> +    @PostMapping("/makeUrl")
굳이 Url을 붙일 필요가 있을까요?

2023-09-27 06:36 UTC, kakao-gray-great commented on src/main/java/com/example/shortURL/domain/Url.java
> +    private int callCount;
id값은 따로 존재하지 않는건가요?
지금 구조면 originUrl을 pk로 잡고 있는데 어떠한 문제점이 있을까요?

2023-09-27 06:36 UTC, kakao-gray-great commented on src/main/java/com/example/shortURL/service/RandomKeyMaker.java
> +}
다른 단축 URL 서비스들에선 어떠한 알고리즘을 사용하는지 한번 공부해보시죠

2023-09-27 06:36 UTC, kakao-gray-great commented on src/main/java/com/example/shortURL/service/ScheduleTask.java
> +}
해당 로직이 service 계층에 들어가는게 맞나요?

2023-09-27 06:36 UTC, kakao-gray-great commented on src/main/java/com/example/shortURL/service/UrlRedirectService.java
> +    }
로거를 생성자 주입하지 않고 사용할 수 있는 방법은 없을까요?

2023-09-27 06:36 UTC, kakao-gray-great commented on src/main/java/com/example/shortURL/vo/OriginUrl.java
> +                (ResponseExtractor<HttpHeaders>) HttpMessage::getHeaders);
restTemplate 말고 다른 대안은 어떤 것들이 있을까요?

2023-09-27 06:36 UTC, kakao-gray-great commented on src/main/java/com/example/shortURL/controller/UrlController.java
> +    }
response dto로 감싸서 응답하는거와 그렇지 않은 것들은 어떠한 차이가 있는건가요?

2023-09-27 06:36 UTC, kakao-gray-great commented on src/main/java/com/example/shortURL/vo/NewUrl.java
> +    private final String baseDomainName = "localhost:8080/";
baseDomainName이 현재는 local인데 실제 배포가 일어나면 localhost가 아니게 될거에요.
그렇다면 어떻게 이 문제를 유연하게 해결할 수 있을까요?

2023-09-29 16:24 UTC, piedra-de-flor commented on src/main/java/com/example/shortURL/configuration/RepositoryConfig.java
> +*/
넵...ㅎㅎ

2023-09-29 16:27 UTC, piedra-de-flor commented on src/main/java/com/example/shortURL/controller/UrlController.java
> +    @PostMapping("/makeUrl")
음 사실 UrlController이기 때문에 Url을 굳이 안써도 이해하기에 아무 문제가 없을 것 같긴 하네요..수정하겠습니다!

2023-09-30 08:21 UTC, piedra-de-flor commented on src/main/java/com/example/shortURL/domain/Url.java
> +    private int callCount;
음 제가 생각하기로는 자동으로 생성되는 클러스터형 인덱스의 크기가 더 많이 요구되고, 가변 길이라서 저장공간의 낭비가 발생할 수 도 있을 것 같습니다.

2023-09-30 08:25 UTC, piedra-de-flor commented on src/main/java/com/example/shortURL/service/ScheduleTask.java
> +}
해당 로직은 스케줄링을 담당하는 로직으로 주어진 기간 마다 해당 비지니스 로직을 수행하야 하기에, 비지니스 로직을 수행하는 Service 계층으로 두었습니다....

2023-09-30 08:30 UTC, piedra-de-flor commented on src/main/java/com/example/shortURL/service/UrlRedirectService.java
> +    }
음 그렇다면 Spring Bean이 아닌 일반적인 싱글톤 객체로 올린다면 생성자 주입없이 사용할 수 있으며, 그저 생성자 주입을 하지 않고자 할 시에는 변수에 주입하거나 setter주입을 할 수 있을거 같습니다.

2023-09-30 08:33 UTC, piedra-de-flor commented on src/main/java/com/example/shortURL/vo/OriginUrl.java
> +                (ResponseExtractor<HttpHeaders>) HttpMessage::getHeaders);
webClient를 사용하거나 HttpURrlConnection을 사용할 수 있을 것 같습니다.

2023-09-30 08:34 UTC, piedra-de-flor commented on src/main/java/com/example/shortURL/controller/UrlController.java
> +    }
어..이건 제가 빠트리고 dto래핑을 해주지 않은 것 같네요..바로 수정하겠습니다.

2023-09-30 08:36 UTC, piedra-de-flor commented on src/main/java/com/example/shortURL/vo/NewUrl.java
> +    private final String baseDomainName = "localhost:8080/";
baseDomainName이라는 VO를 따로 생성하여 NewUrl에서 이 VO를 참조하도록 한다면 실제 배포시에 VO의 값만 변경해주면 유연하게 대처가 가능할 것 같습니다. VO 생성하겠습니다.

2023-09-30 08:42 UTC, piedra-de-flor commented on src/main/java/com/example/shortURL/vo/NewUrl.java
> +    private final String baseDomainName = "localhost:8080/";
음 한번 찾아보니 Spring에서 현재 구동중인 서버의 domain을 받아올 수 있는 방법이 있는 것 같아, domain이 변경될 때 마다 VO의 값을 변경하는 것이 아닌, 해당 서버의 domain을 불러와서 NewUrl에 저장되도록 해야할 것 같습니다.
- HttpServletRequest
- Environment
- ServerProperties

2023-10-08 11:53 UTC, piedra-de-flor commented on src/main/java/com/example/shortURL/service/RandomKeyMaker.java
> +}
base62 인코딩 디코딩 공부하기

2023-10-08 11:55 UTC, merged